name: Rons Test

on: [push]

jobs:
  build:
    runs-on: windows-latest  # ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd "my-app"
          # mvn validate -DbumpPatch
          mvn validate -DbumpPatch compile
          java -cp target/classes com.mycompany.app.App
